# Site settings
title: This is a Podcast
author: B+MC
email: thisisapodcast@fastmail.com
description: "This is a Podcast is a podcast. You will love it."
baseurl: ""
url: "http://thisisapodcast.github.io"
twitter_username: _thisisapodcast
github_username:  thisisapodcast

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
